[project]
name = "bfwai-kimi-agno"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.7.5",
    "gitpython>=3.1.44",
    "openai>=1.97.1",
    "python-dotenv>=1.1.1",
    "streamlit>=1.47.0",
]
